### ISSUE TITLE
||tv002.com^ 导致误杀

### ISSUE THREAD

**Issue by Crystal-RainSlide** [JixunMoe/SimpleList#1]
城通网盘使用类如 http://14859098.143.unicom.data.tv002.com 等域名作为真实下载链接，完整禁止 
 tv002.com 域名会导致误杀。

**Comment by JixunMoe** [comment]
建议不要用这个项目了... 好久没更新了... 我自己也没怎么用（）

**Comment by Crystal-RainSlide** [comment]
好吧，收到…
